FROM python:3.13-alpine3.21

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TZ=Europe/Prague

RUN apk update && apk add --no-cache git cairo openssh libxml2-dev libxslt-dev python3-dev

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN git config --global --add safe.directory /app

ENTRYPOINT ["python3", "bot.py"]

